# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_delete_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
