# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('fecha_pub', models.DateField(verbose_name='fecha de publicacion')),
            ],
        ),
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Articulo'),
        ),
    ]
